spring:
  cloud:
    bus:
      enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  threads:
    virtual:
      enabled: true
  profiles:
    active: default
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          authority-prefix: ""
          authorities-claim-name: authorities
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){red} %clr([%15.15t %X{traceId}-%X{spanId}]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %msg%n"